name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  pull_requests:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
        yarn: true
      
    - name: Install dependencies
      run: yarn install --frozen-lockfile
    
    - name: Build
      run: yarn build
    
    - name: Run tests
      run: yarn test
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: ./build
  
deploy:
  name: Deploy
  needs: build
  runs-on: ubuntu-latest
  if: github.ref == "refs/heads/main"

  steps:
  - name: Download artifacts
    uses: actions/download-artifact@v2
    with:
      name: dist
      path: ./build
  
  - name: Deploy to Pages
    uses: peaceiris/actions-gh-pages@v3
    with:
      github_token: ${{ secrets.GITHUB_TOKEN }}
      publish_dir: ./build
      